---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: none
    show_sql: false