CREATE TABLE `weather` (
  `WEATHER_CITY_ID` int(11) NOT NULL,
  `USER_NAME` varchar(45) DEFAULT NULL,
  `JSON_SERVICE_RESPONSE` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`WEATHER_CITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;